### ISSUE TITLE
Saran wrap needs cap

### ISSUE THREAD

**Issue by fuzheado** [murphykr/recipe#2]
"saran wrap" should be "Saran wrap."

Yes, I am a pedantic grammarian.

**Comment by murphykr** [comment]
Good point! I opted to instead change the text to the generic "plastic wrap" instead.

**Comment by murphykr** [comment]
I thought this was already closed, but I'm just clicking "closed" again. Perhaps I clicked the wrong thing the first time (it's highly likely).
